// web/src/routes/explorer.tsx
/**
 * Explorer screen — Phase 2 React migration.
 *
 * Data sources:
 *   - GET /api/explorer/tree       (typed — ExplorerTreeResponse)
 *   - GET /api/explorer/node/{node_type}/{node_id}  (typed — ExplorerNodeDetail)
 *
 * Layout: 3-pane (domains list | details pane | agent terminal stub)
 * Cadence: tree refetchInterval 30s (matches Svelte page)
 *
 * Svelte parity: web/src/routes/explorer/+page.svelte
 *   - Domain list with nested missions, mission task count, expand-in-place
 *   - Click domain → inline detail (no API call, from tree data)
 *   - Click mission → fetch node detail via API
 *   - Click task → fetch node detail via API (from mission detail task list)
 *   - Status dots: ✓ done/completed, ⟳ in_progress/running, ✗ blocked/failed,
 *                  ○ proposed, ● other
 *   - Search filter across domain names
 *   - Refresh button + last-refreshed timestamp
 *   - Agent terminal pane (stub — ACP wiring out of scope for Phase 2)
 *   - Loading/error/empty states for both tree and node detail
 */

import { apiClient, unwrap } from '@/api/client';
import type { components } from '@/api/schema.gen';
import { queryKeys } from '@/lib/queryKeys';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';

// ── Generated schema types ─────────────────────────────────────────────────────

type ExplorerTreeResponse = components['schemas']['ExplorerTreeResponse'];
type ExplorerDomainNode = components['schemas']['ExplorerDomainNode'];
type ExplorerMissionNode = components['schemas']['ExplorerMissionNode'];
type ExplorerNodeDetail = components['schemas']['ExplorerNodeDetail'];
type ExplorerTask = components['schemas']['ExplorerTask'];

// ── Route ──────────────────────────────────────────────────────────────────────

export const Route = createFileRoute('/explorer')({
  component: ExplorerPage,
});

// ── Selection state ────────────────────────────────────────────────────────────

/** For domains: inline detail from tree data (no API call needed).
 *  For missions and tasks: fetch via ExplorerNodeDetail API. */
type SelectionKey = { type: 'domain' | 'mission' | 'task'; id: string } | null;

// ── Helpers ───────────────────────────────────────────────────────────────────

function statusDot(status?: string | null): string {
  const v = String(status ?? '').toLowerCase();
  if (v === 'done' || v === 'completed') return '✓';
  if (v === 'in_progress' || v === 'running') return '⟳';
  if (v === 'blocked' || v === 'failed') return '✗';
  if (v === 'proposed') return '○';
  return '●';
}

function statusTagVariant(status?: string | null): 'ok' | 'warn' | 'err' | 'accent' | 'default' {
  const v = String(status ?? '').toLowerCase();
  if (v === 'done' || v === 'completed') return 'ok';
  if (v === 'blocked' || v === 'failed') return 'err';
  if (v === 'in_progress' || v === 'running') return 'accent';
  if (v === 'proposed') return 'default';
  return 'default';
}

function fmtDate(s: string | null | undefined): string {
  if (!s) return '—';
  return new Date(s).toLocaleString();
}

function taskCountByStatus(tasks: ExplorerTask[], status: string): number {
  return tasks.filter((t) => String(t.status ?? '').toLowerCase() === status).length;
}

// ── Inline components ─────────────────────────────────────────────────────────

function Tag({
  variant = 'default',
  children,
}: {
  variant?: 'ok' | 'warn' | 'err' | 'accent' | 'purple' | 'default';
  children: React.ReactNode;
}) {
  return <span className={`tag ${variant !== 'default' ? variant : ''}`}>{children}</span>;
}

// ── Tree pane sub-components ──────────────────────────────────────────────────

// Shared row button style — resets button appearance while keeping .row layout
const rowBtnStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '6px',
  width: '100%',
  background: 'none',
  border: 'none',
  padding: '4px 8px',
  textAlign: 'left',
  cursor: 'pointer',
  font: 'inherit',
  color: 'inherit',
};

function MissionRow({
  mission,
  selected,
  onSelect,
}: {
  mission: ExplorerMissionNode;
  selected: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      className="row"
      style={{
        ...rowBtnStyle,
        paddingLeft: '22px',
        background: selected ? 'var(--surface-active, rgba(255,255,255,0.05))' : 'transparent',
      }}
      onClick={onSelect}
      data-testid={`mission-row-${mission.id}`}
    >
      <span className="dim">▸</span>
      <span
        style={{
          flex: 1,
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          fontSize: '11px',
        }}
      >
        {mission.name}
      </span>
      <span className="dim" style={{ fontSize: '10px' }}>
        {mission.task_count}t
      </span>
    </button>
  );
}

function DomainRow({
  domain,
  selected,
  selectedMissionId,
  onSelectDomain,
  onSelectMission,
}: {
  domain: ExplorerDomainNode;
  selected: boolean;
  selectedMissionId: string | null;
  onSelectDomain: () => void;
  onSelectMission: (m: ExplorerMissionNode) => void;
}) {
  return (
    <>
      <button
        type="button"
        className="row"
        style={{
          ...rowBtnStyle,
          background: selected ? 'var(--surface-active, rgba(255,255,255,0.05))' : undefined,
        }}
        onClick={onSelectDomain}
        data-testid={`domain-row-${domain.id}`}
      >
        <span>{statusDot(domain.status)}</span>
        <span
          style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}
        >
          {domain.name}
        </span>
        <span className="dim" style={{ fontSize: '11px' }}>
          {domain.missions.length}m
        </span>
      </button>
      {domain.missions.map((m) => (
        <MissionRow
          key={m.id}
          mission={m}
          selected={selectedMissionId === m.id}
          onSelect={() => onSelectMission(m)}
        />
      ))}
    </>
  );
}

// ── Detail pane sub-components ────────────────────────────────────────────────

function DomainDetail({
  domain,
  onSelectMission,
}: {
  domain: ExplorerDomainNode;
  onSelectMission: (m: ExplorerMissionNode) => void;
}) {
  const variant = statusTagVariant(domain.status);
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
        <strong>{domain.name}</strong>
        <Tag variant={variant}>{domain.status ?? 'unknown'}</Tag>
      </div>
      <p className="muted" style={{ margin: '0 0 10px', fontSize: '12px' }}>
        {domain.description || 'No description.'}
      </p>
      <div
        style={{
          display: 'flex',
          gap: '12px',
          fontSize: '11px',
          color: 'var(--dim)',
          marginBottom: '10px',
        }}
      >
        <span>
          Missions: <span style={{ color: 'var(--text)' }}>{domain.mission_count}</span>
        </span>
        <span>
          Tasks: <span style={{ color: 'var(--text)' }}>{domain.task_count}</span>
        </span>
      </div>
      {domain.missions.length > 0 && (
        <div>
          <p className="section-label">Missions</p>
          {domain.missions.map((m) => (
            <button
              key={m.id}
              type="button"
              className="row"
              style={rowBtnStyle}
              onClick={() => onSelectMission(m)}
            >
              <span className="dim">▸</span>
              <span style={{ flex: 1, fontSize: '12px' }}>{m.name}</span>
              <Tag variant={statusTagVariant(m.status)}>{m.status}</Tag>
              <span className="dim" style={{ fontSize: '10px', marginLeft: '4px' }}>
                {m.task_count}t
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function MissionDetail({
  detail,
  onSelectTask,
}: {
  detail: ExplorerNodeDetail;
  onSelectTask: (taskId: string) => void;
}) {
  const m = detail.mission;
  const tasks = (detail.tasks ?? []) as ExplorerTask[];
  const variant = statusTagVariant(m?.status);

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
        <strong>{m?.name ?? 'Mission'}</strong>
        <Tag variant={variant}>{m?.status ?? 'unknown'}</Tag>
      </div>
      <p className="muted" style={{ margin: '0 0 10px', fontSize: '12px' }}>
        {m?.description || 'No description.'}
      </p>
      <div
        style={{
          display: 'flex',
          gap: '12px',
          fontSize: '11px',
          color: 'var(--dim)',
          marginBottom: '10px',
        }}
      >
        <span>Tasks: {tasks.length}</span>
        <span>In progress: {taskCountByStatus(tasks, 'in_progress')}</span>
        <span>Blocked: {taskCountByStatus(tasks, 'blocked')}</span>
      </div>
      {tasks.length > 0 ? (
        tasks.map((t) => (
          <div key={t.id} style={{ padding: '7px 0', borderBottom: '1px solid var(--border)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>{statusDot(t.status)}</span>
              <strong style={{ fontSize: '12px', flex: 1 }}>{t.title}</strong>
              <Tag variant={statusTagVariant(t.status)}>{t.status ?? 'unknown'}</Tag>
            </div>
            <p className="muted" style={{ margin: '3px 0 0', fontSize: '11px' }}>
              {t.description || 'No description.'}
            </p>
            <button
              type="button"
              className="ghost"
              style={{ marginTop: '5px', fontSize: '11px' }}
              onClick={() => onSelectTask(String(t.public_id ?? t.id))}
              data-testid={`open-task-${t.id}`}
            >
              Open Task
            </button>
          </div>
        ))
      ) : (
        <p className="muted" style={{ fontSize: '12px' }}>
          No sub-tasks.
        </p>
      )}
    </div>
  );
}

function TaskDetail({ detail }: { detail: ExplorerNodeDetail }) {
  const t = detail.task;
  const variant = statusTagVariant(t?.status);
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
        <strong>{t?.title ?? 'Task'}</strong>
        <Tag variant={variant}>{t?.status ?? 'unknown'}</Tag>
      </div>
      <p className="muted" style={{ margin: '0 0 10px', fontSize: '12px' }}>
        {t?.description || 'No description.'}
      </p>
      {t && (
        <dl className="policy-meta">
          <dt>Public ID</dt>
          <dd style={{ fontFamily: 'monospace', fontSize: '11px', color: 'var(--accent)' }}>
            {t.public_id}
          </dd>
          <dt>Owner</dt>
          <dd>{t.owner || '—'}</dd>
          <dt>Contributors</dt>
          <dd>{t.contributors || '—'}</dd>
          <dt>Mission</dt>
          <dd style={{ fontSize: '11px', color: 'var(--dim)' }}>{t.mission_id}</dd>
          <dt>Created</dt>
          <dd>{fmtDate(t.created_at)}</dd>
          <dt>Updated</dt>
          <dd>{fmtDate(t.updated_at)}</dd>
        </dl>
      )}
      <details style={{ marginTop: '12px' }}>
        <summary style={{ fontSize: '11px', color: 'var(--dim)', cursor: 'pointer' }}>
          Raw JSON
        </summary>
        <pre style={{ fontSize: '11px', marginTop: '6px' }}>{JSON.stringify(detail, null, 2)}</pre>
      </details>
    </div>
  );
}

// ── Unassigned missions ────────────────────────────────────────────────────────

function UnassignedMissions({
  missions,
  selectedId,
  onSelect,
}: {
  missions: ExplorerMissionNode[];
  selectedId: string | null;
  onSelect: (m: ExplorerMissionNode) => void;
}) {
  if (missions.length === 0) return null;
  return (
    <>
      <div
        className="row"
        style={{
          color: 'var(--dim)',
          fontSize: '10px',
          textTransform: 'uppercase',
          cursor: 'default',
        }}
      >
        Unassigned
      </div>
      {missions.map((m) => (
        <MissionRow
          key={m.id}
          mission={m}
          selected={selectedId === m.id}
          onSelect={() => onSelect(m)}
        />
      ))}
    </>
  );
}

// ── Main page ──────────────────────────────────────────────────────────────────

// Named export for direct use in tests (avoids router context requirement)
export function ExplorerPage() {
  const queryClient = useQueryClient();

  const [searchInput, setSearchInput] = useState('');
  const [selection, setSelection] = useState<SelectionKey>(null);

  // Track domain selection separately (inline, no API call)
  const [selectedDomainNode, setSelectedDomainNode] = useState<ExplorerDomainNode | null>(null);

  // ── Tree query ─────────────────────────────────────────────────────────────
  const treeQuery = useQuery<ExplorerTreeResponse>({
    queryKey: queryKeys.explorer.tree(),
    queryFn: () => unwrap(apiClient.GET('/api/explorer/tree')),
    refetchInterval: 30_000,
  });

  // ── Node detail query ──────────────────────────────────────────────────────
  // Only enabled when a mission or task is selected (domains use inline data)
  const nodeQuery = useQuery<ExplorerNodeDetail>({
    queryKey: selection
      ? queryKeys.explorer.node(selection.type, selection.id)
      : (['__explorer_none__'] as const),
    queryFn: () =>
      unwrap(
        apiClient.GET('/api/explorer/node/{node_type}/{node_id}', {
          params: { path: { node_type: selection?.type ?? '', node_id: selection?.id ?? '' } },
        }),
      ),
    enabled: !!selection && selection.type !== 'domain',
    refetchOnWindowFocus: false,
  });

  // ── Derived ────────────────────────────────────────────────────────────────
  const tree = treeQuery.data;
  const domains = tree?.domains ?? [];
  const unassigned = tree?.unassigned_missions ?? [];

  const filteredDomains = searchInput
    ? domains.filter((d) => d.name.toLowerCase().includes(searchInput.toLowerCase()))
    : domains;

  const lastRefreshed =
    treeQuery.dataUpdatedAt > 0 ? new Date(treeQuery.dataUpdatedAt).toLocaleTimeString() : '';

  // ── Selection handlers ─────────────────────────────────────────────────────

  function selectDomain(d: ExplorerDomainNode) {
    setSelectedDomainNode(d);
    setSelection(null); // domain details come from tree data, no API call
  }

  function selectMission(m: ExplorerMissionNode) {
    setSelectedDomainNode(null);
    setSelection({ type: 'mission', id: m.id });
  }

  function selectTask(taskId: string) {
    setSelectedDomainNode(null);
    setSelection({ type: 'task', id: taskId });
  }

  function refreshTree() {
    queryClient.invalidateQueries({ queryKey: queryKeys.explorer.tree() });
  }

  // ── Determine selected mission id for highlighting ─────────────────────────
  const selectedMissionId = selection?.type === 'mission' ? selection.id : null;
  const selectedDomainId = selectedDomainNode?.id ?? null;

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div
      style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' }}
      data-testid="explorer-page"
    >
      {/* Top filter bar */}
      <div className="gov-bar">
        <span className="gov-title" style={{ marginRight: '4px' }}>
          Explorer
        </span>
        <input
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
          placeholder="filter domains…"
          style={{ width: '180px' }}
          data-testid="search-input"
        />
        <button type="button" className="ghost" onClick={refreshTree} data-testid="refresh-btn">
          Refresh
        </button>
        {lastRefreshed && (
          <span className="muted" style={{ fontSize: '11px' }}>
            updated {lastRefreshed}
          </span>
        )}
      </div>

      {/* Tree loading */}
      {treeQuery.isLoading && (
        <div style={{ padding: '12px' }}>
          <p className="muted" data-testid="loading-state">
            ⟳ Loading explorer…
          </p>
        </div>
      )}

      {/* Tree error */}
      {treeQuery.isError && (
        <div style={{ padding: '12px' }}>
          <p className="error" data-testid="error-state">
            ✗ Failed to load explorer — {(treeQuery.error as Error)?.message ?? 'unknown error'}
          </p>
        </div>
      )}

      {/* 3-pane layout — shown once tree resolves with data */}
      {!treeQuery.isLoading &&
        !treeQuery.isError &&
        (domains.length > 0 || unassigned.length > 0) && (
          <div className="pane-row" style={{ flex: 1, minHeight: 0 }}>
            {/* Pane 1: Domains + missions tree */}
            <div className="pane" style={{ width: '220px', flexShrink: 0 }}>
              <div className="pane-header">
                <span className="pane-title">Domains</span>
                <span className="dim">{filteredDomains.length}</span>
              </div>
              <div className="pane-body" style={{ overflow: 'auto' }}>
                {filteredDomains.length > 0 ? (
                  filteredDomains.map((d) => (
                    <DomainRow
                      key={d.id}
                      domain={d}
                      selected={selectedDomainId === d.id}
                      selectedMissionId={selectedMissionId}
                      onSelectDomain={() => selectDomain(d)}
                      onSelectMission={selectMission}
                    />
                  ))
                ) : (
                  <div className="row">
                    <span className="muted" style={{ fontSize: '12px' }}>
                      No domains yet.
                    </span>
                  </div>
                )}
                <UnassignedMissions
                  missions={unassigned}
                  selectedId={selectedMissionId}
                  onSelect={selectMission}
                />
              </div>
            </div>

            {/* Pane 2: Detail */}
            <div className="pane" style={{ flex: 1, minWidth: 0 }}>
              <div className="pane-header">
                <span className="pane-title">Details</span>
                {nodeQuery.isFetching && (
                  <span className="muted" style={{ fontSize: '10px' }}>
                    ⟳
                  </span>
                )}
              </div>
              <div className="pane-body" style={{ padding: '10px', overflow: 'auto' }}>
                {/* Node detail loading */}
                {nodeQuery.isLoading && selection && selection.type !== 'domain' && (
                  <p className="muted" data-testid="detail-loading-state">
                    ⟳ Loading…
                  </p>
                )}

                {/* Node detail error */}
                {nodeQuery.isError && (
                  <p className="error" data-testid="detail-error-state">
                    ✗ Failed to load detail —{' '}
                    {(nodeQuery.error as Error)?.message ?? 'unknown error'}
                  </p>
                )}

                {/* Domain detail (inline from tree) */}
                {!nodeQuery.isLoading && selectedDomainNode && !selection && (
                  <DomainDetail domain={selectedDomainNode} onSelectMission={selectMission} />
                )}

                {/* Mission or task detail (from API) */}
                {!nodeQuery.isLoading && !nodeQuery.isError && nodeQuery.data && (
                  <>
                    {nodeQuery.data.node_type === 'mission' && (
                      <MissionDetail detail={nodeQuery.data} onSelectTask={selectTask} />
                    )}
                    {nodeQuery.data.node_type === 'task' && <TaskDetail detail={nodeQuery.data} />}
                    {nodeQuery.data.node_type !== 'mission' &&
                      nodeQuery.data.node_type !== 'task' && (
                        <pre style={{ fontSize: '11px' }}>
                          {JSON.stringify(nodeQuery.data, null, 2)}
                        </pre>
                      )}
                  </>
                )}

                {/* Prompt when nothing selected */}
                {!nodeQuery.isLoading && !selectedDomainNode && !selection && (
                  <p className="muted" data-testid="detail-empty-state">
                    Select a domain or mission.
                  </p>
                )}
              </div>
            </div>

            {/* Pane 3: Agent terminal stub */}
            <div className="pane" style={{ width: '320px', flexShrink: 0 }}>
              <div className="pane-header">
                <span className="pane-title">Agent Terminal</span>
                <span className="muted" style={{ fontSize: '10px' }}>
                  Phase 3
                </span>
              </div>
              <div className="pane-body">
                <div
                  style={{ padding: '10px', display: 'flex', flexDirection: 'column', gap: '6px' }}
                >
                  <input placeholder="node id (e.g. epyc)" />
                  <input placeholder="agent id" />
                  <button type="button" className="ghost" disabled style={{ fontSize: '11px' }}>
                    Attach
                  </button>
                  <p className="muted" style={{ fontSize: '11px', marginTop: '4px' }}>
                    ACP terminal attach coming in Phase 3.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

      {/* Full empty state when tree resolves but has no domains */}
      {!treeQuery.isLoading &&
        !treeQuery.isError &&
        domains.length === 0 &&
        unassigned.length === 0 && (
          <div className="empty-state" data-testid="empty-state">
            <div className="empty-icon">⊙</div>
            <div className="empty-title">No domains or missions</div>
            <div className="empty-body">
              Create a domain with <code>edgeplane domain create</code> to get started.
            </div>
          </div>
        )}
    </div>
  );
}

// web/src/routes/explorer/+page.svelte
<script lang="ts">
  import { createQuery, useQueryClient } from '@tanstack/svelte-query';
  import { useAuthState } from '$lib/stores/auth-state.svelte';
  import { queryKeys } from '$lib/queryKeys';
  import { fetchTree, fetchNode } from '$lib/api';
  import AgentTerminal from '$lib/components/AgentTerminal.svelte';

  const queryClient = useQueryClient();
  const auth = useAuthState();

  let searchInput = $state('');
  let selectedNodeType = $state<'domain' | 'mission' | 'task' | null>(null);
  let selectedNodeKey = $state<{ type: 'domain' | 'mission' | 'task'; id: string } | null>(null);
  let selectedDomainData = $state<{ domain: unknown; missions: unknown[]; tasks: unknown[] } | null>(null);

  const treeQuery = createQuery(() => ({
    queryKey: queryKeys.explorer.tree(),
    queryFn: () => fetchTree(auth.currentToken || undefined),
    enabled: auth.isLoggedIn
  }));

  const nodeQuery = createQuery(() => ({
    queryKey: selectedNodeKey
      ? queryKeys.explorer.node(selectedNodeKey.type, selectedNodeKey.id)
      : (['__explorer_none__'] as const),
    queryFn: () => fetchNode(selectedNodeKey!.type, selectedNodeKey!.id, auth.currentToken || undefined),
    enabled: auth.isLoggedIn && !!selectedNodeKey
  }));

  let filteredDomains = $derived(
    ((treeQuery.data?.domains ?? []) as unknown[]).filter(
      (d: unknown) => !searchInput || (d as { name?: string }).name?.toLowerCase().includes(searchInput.toLowerCase())
    )
  );

  let lastRefreshed = $derived(
    treeQuery.dataUpdatedAt > 0 ? new Date(treeQuery.dataUpdatedAt).toLocaleTimeString() : ''
  );

  let explorerBusy = $derived(nodeQuery.isFetching && !!selectedNodeKey);

  let selectedNodeData = $derived.by(() => {
    if (selectedNodeType === 'domain') return selectedDomainData;
    return (nodeQuery.data as Record<string, unknown>) ?? null;
  });

  function statusClass(status?: string) {
    const v = String(status ?? '').toLowerCase();
    if (v === 'done' || v === 'completed') return 'status-done';
    if (v === 'blocked') return 'status-blocked';
    if (v === 'in_progress') return 'status-progress';
    return 'status-proposed';
  }

  function statusTagClass(status?: string) {
    const v = String(status ?? '').toLowerCase();
    if (v === 'done' || v === 'completed') return 'ok';
    if (v === 'blocked' || v === 'failed') return 'err';
    if (v === 'in_progress' || v === 'running') return 'accent';
    return 'dim';
  }

  function statusDot(status?: string) {
    const v = String(status ?? '').toLowerCase();
    if (v === 'done' || v === 'completed') return '✓';
    if (v === 'in_progress' || v === 'running') return '⟳';
    if (v === 'blocked' || v === 'failed') return '✗';
    if (v === 'proposed') return '○';
    return '●';
  }

  function taskCountByStatus(tasks: unknown[] = [], status: string) {
    return (tasks as { status?: string }[]).filter(t => String(t.status ?? '').toLowerCase() === status).length;
  }

  function selectExplorerNode(type: 'domain' | 'mission' | 'task', node: unknown) {
    selectedNodeType = type;
    if (type === 'domain') {
      selectedDomainData = {
        domain: node,
        missions: (node as { missions?: unknown[] }).missions ?? [],
        tasks: []
      };
      selectedNodeKey = null;
      return;
    }
    selectedDomainData = null;
    const nodeId =
      type === 'task'
        ? String((node as { public_id?: unknown; id?: unknown }).public_id ?? (node as { id?: unknown }).id ?? '')
        : String((node as { id?: unknown }).id ?? '');
    selectedNodeKey = nodeId ? { type, id: nodeId } : null;
  }

  function selectDomain(d: unknown) { return selectExplorerNode('domain', d); }
  function selectMission(m: unknown) { return selectExplorerNode('mission', m); }
  function selectTask(t: unknown) { return selectExplorerNode('task', t); }

  function refreshTree() {
    queryClient.invalidateQueries({ queryKey: queryKeys.explorer.tree() });
  }

  // Agent terminal drawer — manual node/agent entry MVP. Future work surfaces
  // these as a node type in the tree.
  let terminalOpen = $state(false);
  let terminalNodeId = $state('');
  let terminalAgentId = $state('');
  let activeTerminal = $state<{ nodeId: string; agentId: string } | null>(null);

  function openAgentTerminal() {
    if (!terminalNodeId || !terminalAgentId) return;
    activeTerminal = { nodeId: terminalNodeId, agentId: terminalAgentId };
    terminalOpen = true;
  }

  function closeAgentTerminal() {
    terminalOpen = false;
    activeTerminal = null;
  }
</script>

<div class="explorer-page">

  <!-- top filter bar -->
  <div class="explorer-bar">
    <span class="explorer-bar-title">Explorer</span>
    <input bind:value={searchInput} placeholder="filter domains…" style="width:180px;" />
    <button class="ghost" onclick={refreshTree}>Refresh</button>
    {#if lastRefreshed}<span class="muted" style="font-size:11px;">updated {lastRefreshed}</span>{/if}
  </div>

  <!-- 3-pane layout -->
  <div class="pane-row" style="flex:1; min-height:0;">

    <!-- pane 1: domains -->
    <div class="pane" style="width:220px; flex-shrink:0;">
      <div class="pane-header">
        <span class="pane-title">Domains</span>
        <span class="dim">{filteredDomains.length}</span>
      </div>
      <div class="pane-body">
        {#each filteredDomains as domain}
          <div class="row" role="button" tabindex="0"
            onclick={() => selectDomain(domain)}
            onkeydown={(e) => e.key === 'Enter' && selectDomain(domain)}>
            <span>{statusDot((domain as { status?: string }).status)}</span>
            <span style="flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">{(domain as { name?: string }).name}</span>
            <span class="dim" style="font-size:11px;">{(domain as { missions?: unknown[] }).missions?.length ?? 0}m</span>
          </div>
          {#if (domain as { missions?: unknown[] }).missions?.length}
            {#each (domain as { missions: unknown[] }).missions as mission}
              <div class="row" role="button" tabindex="0" style="padding-left:22px; background:transparent;"
                onclick={() => selectMission(mission)}
                onkeydown={(e) => e.key === 'Enter' && selectMission(mission)}>
                <span class="dim">▸</span>
                <span style="flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:11px;">{(mission as { name?: string }).name}</span>
                <span class="dim" style="font-size:10px;">{(mission as { task_count?: number; recent_tasks?: unknown[] }).task_count ?? (mission as { recent_tasks?: unknown[] }).recent_tasks?.length ?? 0}t</span>
              </div>
            {/each}
          {/if}
        {:else}
          <div class="row"><span class="muted">No domains yet.</span></div>
        {/each}
      </div>
    </div>

    <!-- pane 2: details -->
    <div class="pane" style="flex:1; min-width:0;">
      <div class="pane-header">
        <span class="pane-title">Details</span>
      </div>
      <div class="pane-body" style="padding:10px;">
        {#if explorerBusy}
          <p class="muted">⟳ Loading…</p>
        {:else if selectedNodeData}
          {#if selectedNodeType === 'domain' && (selectedNodeData as { domain?: unknown }).domain}
            {@const d = (selectedNodeData as { domain: { name?: string; status?: string; description?: string; task_count?: number }; missions?: unknown[] })}
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;">
              <strong>{d.domain.name}</strong>
              <span class="tag {statusTagClass(d.domain.status)}">{d.domain.status ?? 'unknown'}</span>
            </div>
            <p class="muted" style="margin:0 0 10px;">{d.domain.description || 'No description.'}</p>
            <div style="display:flex; gap:12px; font-size:11px; color:var(--dim);">
              <span>Missions: <span class="text">{d.missions?.length ?? 0}</span></span>
              <span>Tasks: <span class="text">{d.domain.task_count ?? 0}</span></span>
            </div>
          {:else if selectedNodeType === 'mission' && (selectedNodeData as { mission?: unknown }).mission}
            {@const m = (selectedNodeData as { mission: { name?: string; status?: string; description?: string }; tasks?: unknown[] })}
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;">
              <strong>{m.mission.name}</strong>
              <span class="tag {statusTagClass(m.mission.status)}">{m.mission.status ?? 'unknown'}</span>
            </div>
            <p class="muted" style="margin:0 0 10px;">{m.mission.description || 'No description.'}</p>
            <div style="display:flex; gap:12px; font-size:11px; color:var(--dim); margin-bottom:10px;">
              <span>Tasks: {m.tasks?.length ?? 0}</span>
              <span>In progress: {taskCountByStatus(m.tasks ?? [], 'in_progress')}</span>
              <span>Blocked: {taskCountByStatus(m.tasks ?? [], 'blocked')}</span>
            </div>
            {#each m.tasks ?? [] as task}
              <div class="task-row">
                <div style="display:flex; align-items:center; gap:6px;">
                  <span>{statusDot((task as { status?: string }).status)}</span>
                  <strong style="font-size:12px;">{(task as { title?: string }).title}</strong>
                  <span class="tag {statusTagClass((task as { status?: string }).status)}" style="margin-left:auto;">{(task as { status?: string }).status ?? 'unknown'}</span>
                </div>
                <p class="muted" style="margin:3px 0 0; font-size:11px;">{(task as { description?: string }).description || 'No description.'}</p>
                <button class="ghost" style="margin-top:5px; font-size:11px;" onclick={() => selectTask(task)}>Open Task</button>
              </div>
            {:else}
              <p class="muted">No sub-tasks.</p>
            {/each}
          {:else if selectedNodeType === 'task' && (selectedNodeData as { task?: unknown }).task}
            {@const t = (selectedNodeData as { task: { title?: string; status?: string; description?: string } })}
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;">
              <strong>{t.task.title}</strong>
              <span class="tag {statusTagClass(t.task.status)}">{t.task.status ?? 'unknown'}</span>
            </div>
            <p class="muted" style="margin:0 0 10px;">{t.task.description || 'No description.'}</p>
            <pre style="font-size:11px;">{JSON.stringify(selectedNodeData, null, 2)}</pre>
          {:else}
            <pre style="font-size:11px;">{JSON.stringify(selectedNodeData, null, 2)}</pre>
          {/if}
        {:else}
          <p class="muted">Select a domain or mission.</p>
        {/if}
      </div>
    </div>

    <!-- pane 3: agent terminal -->
    <div class="pane" style="width:320px; flex-shrink:0;">
      <div class="pane-header">
        <span class="pane-title">Agent Terminal</span>
        {#if !terminalOpen}
          <button class="ghost" style="font-size:11px; padding:2px 6px;" onclick={openAgentTerminal} disabled={!terminalNodeId || !terminalAgentId}>Attach</button>
        {:else}
          <button class="ghost" style="font-size:11px; padding:2px 6px;" onclick={closeAgentTerminal}>Detach</button>
        {/if}
      </div>
      <div class="pane-body">
        {#if !terminalOpen}
          <div style="padding:10px; display:flex; flex-direction:column; gap:6px;">
            <input bind:value={terminalNodeId} placeholder="node id (e.g. epyc)" />
            <input bind:value={terminalAgentId} placeholder="agent id" />
          </div>
        {:else if activeTerminal && auth.currentToken}
          <div style="height:100%;">
            <AgentTerminal
              nodeId={activeTerminal.nodeId}
              agentId={activeTerminal.agentId}
              token={auth.currentToken}
            />
          </div>
        {/if}
      </div>
    </div>

  </div>
</div>

<style>
  .explorer-page {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }

  .explorer-bar {
    height: 36px;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 0 12px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
  }

  .explorer-bar-title {
    font-size: 12px;
    font-weight: 600;
    color: var(--text);
    margin-right: 4px;
  }

  .task-row {
    padding: 7px 0;
    border-bottom: 1px solid var(--border);
  }

  .task-row:last-child {
    border-bottom: none;
  }
</style>
